#!/usr/bin/python -O

import PyTango as Tg
import telnetlib

import logging
from common import *
import os

def backup_host(host, log=None):
    if log is None:
        log = logging.getLogger('backup_host.%s' % host)

    tel = BrukerRemote(host)
    tel.cd('/BRUKER/configurations')
    path = 'backup/%s/' % host
    try:
        os.makedirs(path)
    except OSError, e:
        if e.errno==17:
            pass
        else:
            raise
    fname = 'current.tar.gz'
    with open(path+fname, 'w') as out:
            out.write(tel.cat(fname))
    log.info('backup %s finished' % host)


if __name__=="__main__":
        import sys
        logging.basicConfig(level=logging.INFO)
        logging.getLogger('BrukerRemote').setLevel(logging.ERROR)
        for h in get_hosts():
            try:
                backup_host(h)
            except Exception, exc:
                print h, exc